apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "e-market.fullname" . }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /orders
            pathType: Prefix
            backend:
              service:
                name: {{.Values.facadeService}}
                port:
                  number: {{ .Values.service.port }}