apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user-profile-chart.fullname" . }}
  labels:
    {{- include "user-profile-chart.labels" . | nindent 4 }} 
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "user-profile-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "user-profile-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/
              port: 80