replicaCount: 1

image: tselofan/user-profile

service:
  #Для работы туннеля нужен сервис LoadBalancer
  type: LoadBalancer
  port: 80

autoscaling:
  enabled: false

serviceAccount:
  create: false

secrets:
  connectionstring: ""