apiVersion: skaffold/v2beta2
kind: Config
metadata:
  name: auth
build:
  tagPolicy:
    sha256: { }
  artifacts:
    - image: tselofan/auth
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: auth
        chartPath: chart/auth
        valuesFiles:
          - chart/auth/values.yaml
        version: 0.1.0
        values: 
          image: tselofan/auth
